name: publish

on:
  push:
    branches:
      - master

jobs:
  publish_all:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org
      - run: npm i -g npm can-npm-publish
      - run: npm i
      - run: npm run build
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          can-npm-publish ./core --verbose && npm publish ./core
          can-npm-publish ./http --verbose && npm publish ./http
          can-npm-publish ./snabbdom && npm publish ./snabbdom
          can-npm-publish ./next && npm publish ./next
